name: Xcode - Build and Analyze

on:
  push:
    branches: ["test"]
  pull_request:
    branches: ["test"]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Prebuild iOS project
        run: npx expo prebuild --platform ios

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
          pod update

      - name: Select Xcode
        run: |
          ls
          sudo Xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer

      - name: Build
        run: xcodebuild clean build -workspace tmschat.xcworkspace -scheme tmschat -destination 'platform=iOS Simulator,name=iPhone 16 example,OS=18.0'
